# Generated by Django 2.0.9 on 2018-10-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_auto_20181023_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='Pico y Placa?'),
        ),
    ]
